### PR TITLE
Subregion addition

### PR DESCRIPTION
**Pull request by evasinha**

### CODE REVIEW

**Comment by evasinha** [comment]
@kvcalvin or @rplzzz Can either one of you suggest why the pull request failed both test? I did run the `devtools::test()` and `devtools::check()` on my computer before uploading the files and both test and check passed.

**Comment by rplzzz** [comment]
It looks like you're getting a bunch of warnings when generating the package documentation because you added a `SUBREGION` argument to a bunch of functions but didn't document it.  It probably passed on your local machine because the local run wasn't set to treat warnings as errors, but on Travis warnings are treated as errors.  

Here's the list of warnings you got:

```
odoc mismatches from documentation object 'LandAllocator_setup':
LandAllocator_setup
  Code: function(aLandAllocator, aScenarioInfo, agData = NULL,
                 SUBREGION = NULL)
  Docs: function(aLandAllocator, aScenarioInfo, agData = NULL)
  Argument names in code not in docs:
    SUBREGION
Codoc mismatches from documentation object 'ReadData_AgProd':
ReadData_AgProd
  Code: function(aRegionName, ascentype, SUBREGION = NULL,
                 subregionData = NULL)
  Docs: function(aRegionName, ascentype)
  Argument names in code not in docs:
    SUBREGION subregionData
Codoc mismatches from documentation object 'ReadData_LN0':
ReadData_LN0
  Code: function(aRegionName, SUBREGION = NULL, subregionData = NULL)
  Docs: function(aRegionName)
  Argument names in code not in docs:
    SUBREGION subregionData
Codoc mismatches from documentation object 'ReadData_LN1_LeafChildren':
ReadData_LN1_LeafChildren
  Code: function(aRegionName, SUBREGION = NULL, subregionData = NULL)
  Docs: function(aRegionName)
  Argument names in code not in docs:
    SUBREGION subregionData
Codoc mismatches from documentation object 'ReadData_LN1_Node':
ReadData_LN1_Node
  Code: function(aRegionName, SUBREGION = NULL, subregionData = NULL)
  Docs: function(aRegionName)
  Argument names in code not in docs:
    SUBREGION subregionData
Codoc mismatches from documentation object 'ReadData_LN2_LandLeaf':
ReadData_LN2_LandLeaf
  Code: function(aRegionName, SUBREGION = NULL, subregionData = NULL)
  Docs: function(aRegionName)
  Argument names in code not in docs:
    SUBREGION subregionData
Codoc mismatches from documentation object 'ReadData_LN2_Node':
ReadData_LN2_Node
  Code: function(aRegionName, SUBREGION = NULL, subregionData = NULL)
  Docs: function(aRegionName)
  Argument names in code not in docs:
    SUBREGION subregionData
Codoc mismatches from documentation object 'ReadData_LN2_UnmanagedLandLeaf':
ReadData_LN2_UnmanagedLandLeaf
  Code: function(aRegionName, SUBREGION = NULL, subregionData = NULL)
  Docs: function(aRegionName)
  Argument names in code not in docs:
    SUBREGION subregionData
Codoc mismatches from documentation object 'ReadData_LN3_LandLeaf':
ReadData_LN3_LandLeaf
  Code: function(aRegionName, SUBREGION = NULL, subregionData = NULL)
  Docs: function(aRegionName)
  Argument names in code not in docs:
    SUBREGION subregionData
Codoc mismatches from documentation object 'ReadData_LN3_Node':
ReadData_LN3_Node
  Code: function(aRegionName, SUBREGION = NULL, subregionData = NULL)
  Docs: function(aRegionName)
  Argument names in code not in docs:
    SUBREGION subregionData
Codoc mismatches from documentation object 'ReadData_LN3_UnmanagedLandLeaf':
ReadData_LN3_UnmanagedLandLeaf
  Code: function(aRegionName, SUBREGION = NULL, subregionData = NULL)
  Docs: function(aRegionName)
  Argument names in code not in docs:
    SUBREGION subregionData
Codoc mismatches from documentation object 'get_AgProdChange':
get_AgProdChange
  Code: function(ascentype, SUBREGION = NULL)
  Docs: function(ascentype)
  Argument names in code not in docs:
    SUBREGION
```

**Comment by evasinha** [comment]
@rplzzz I committed all documentation files and now travis-ci is passing. How do I increase code coverage for new addition in `read_data.R`? I think all I need is test with `SUBREGION != NULL` but I am not sure how and where to add this test.

**Comment by rplzzz** [comment]
@evasinha It looks like you edited the .Rd files directly, but normally we allow those to be generated automatically by Roxygen from the specially formatted functions that you see at the beginning of each function.  In this case you want to add an `@param` line for your new parameter and rerun the documentation generator (ctrl-shift-D in Rstudio, or `devtools::document()` from the console)

If you don't mind, could you read through the book _R Packages_, by Hadley Wickham?  It's not very long, and the full text is available for free online:   http://r-pkgs.had.co.nz/
It describes everything you need to know about putting together packages in R.  There is a section on tests that should answer your other question about where to add a test for your new code.

**Comment by evasinha** [comment]
@rplzzz Thanks for helping me figure out what is causing the errors. I had not updated any of the .Rd files manually and had added `@param` before any function that was modified and information about the additional parameter being passed to the function. The .Rd files were automatically updated when I ran the `devtools::test()` and `devtools::check()` commands. Since the .Rd files were automatically updated on my computer, I was hoping that the same will happen on the github repo when I commit changes to the R files, which is why during my first commit I had not added/committed/pushed the .Rd files but then `travis-ci` was failing.

I will read the book on R packages suggested by you to figure out where I am making a mistake.

**Comment by rplzzz** [comment]
I see.  That explains why only the .Rd files were updated in that last commit.

I generally adjust the settings on Rstudio to cause the documentation to be rebuilt whenever I build and reload the package.  I'm not sure why that isn't the default, since running the documentation function only takes a few seconds.

**Pull request merged**
